# This file was generated by GoReleaser. DO NOT EDIT.
cask "conflow" do
  version "0.6.1"

  on_macos do
    on_intel do
      sha256 "a4f1971824286010db59b63f0a741026ac91cd98dbb7a6688ba8b1b773b1e14b"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd20e4df1257f21d72d9281e8a35c6d3adf5eb9a5d6c48b4c27d71de263d24db"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "69526ce0968b98533c5afafae0448774f2f226e28fb39e738d608a3d0d8c9963"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f40b662aa72d68fbaeac19e6b1fe02ad3615a353bc16daf4e6680e6b48a7c57c"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "conflow"
  desc "Local-first ConfigOps workbench for Firebase Remote Config"
  homepage "https://github.com/ConteMan/conflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "conflow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/conflow"]
    end
  end

  # No zap stanza required

end
