# This file was generated by GoReleaser. DO NOT EDIT.
cask "conflow" do
  version "0.5.3"

  on_macos do
    on_intel do
      sha256 "5bc12324e6d03b59d16b50190acd7864373f1ae3ff673cea18707280d32bc630"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97ed5fe3d3e1e764623d6adfb4a385809937a25b6706fb617415c01ef285acf7"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d62fa2d65c1840e7536f0865ecc8cb70627f4ee131fc2225ddecb878777a6d41"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "df5a0c41e8dca7aa658cae0ce6b3df3b200e1bffd1406c59fbfc9e2893e41e78"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "conflow"
  desc "Local-first ConfigOps workbench for Firebase Remote Config"
  homepage "https://github.com/ConteMan/conflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "conflow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/conflow"]
    end
  end

  # No zap stanza required

end
