# This file was generated by GoReleaser. DO NOT EDIT.
cask "conflow" do
  version "0.5.2"

  on_macos do
    on_intel do
      sha256 "5e7fa2f526ac7b7b644da364d5da15e7f98cd591aa40ffafba2617b53a4118c6"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a17e53657172cd52666fb17425d9f94862fe58d1f521fe2ff950833e30d0309"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "659efcdcd3c39c503e5344c44e2108dfb4b9da0399192f1bc5ff4e3e906b5fa0"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0003e2cc8e66f335e0cc204f5be353136ce528b0c87d103642ebe3f85c54910"
      url "https://github.com/ConteMan/conflow/releases/download/v#{version}/conflow_#{version}_linux_arm64.tar.gz"
    end
  end

  name "conflow"
  desc "Local-first ConfigOps workbench for Firebase Remote Config"
  homepage "https://github.com/ConteMan/conflow"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "conflow"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/conflow"]
    end
  end

  # No zap stanza required

end
