# This file was generated by GoReleaser. DO NOT EDIT.
cask "repolens" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "80f4f68e36bb384f40fe107ca987eddb1237c90af3477bd1a1a97aa891877b15"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "782e0f923dc39fca87a9533816fc94377755c30cc816810271ad5b9903a14725"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "53e1804caae5b8c9f1103fee7c73e158a6da29b6a3b5aedeef39c56775b21906"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9dc6dd22d072f8ef1211667fef694ac8e075f694467fb8bb904ec8207de31fe"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repolens"
  desc "Turn any Git repository into a browsable static site"
  homepage "https://github.com/ConteMan/repolens"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repolens"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repolens"]
    end
  end

  # No zap stanza required

end
