# This file was generated by GoReleaser. DO NOT EDIT.
cask "repolens" do
  version "1.3.1-rc.1"

  on_macos do
    on_intel do
      sha256 "4c10fed11b03777f2a50390483e7a07c8a1b087a0907725cdb0f4553e045affb"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d19e9b5f70de3431739944f3e89eadd44395867956fbe4289918cdb337dc729"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b057d28d59f22cc67956e7fbbaaa5f55a841113aa29befd5dd60daf1c34b8271"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "884f3bc0a12a9591f862e5371ead027936e406d91ebb52aa9670942da8885820"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repolens"
  desc "Turn any Git repository into a browsable static site"
  homepage "https://github.com/ConteMan/repolens"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repolens"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repolens"]
    end
  end

  # No zap stanza required

end
