# This file was generated by GoReleaser. DO NOT EDIT.
cask "repolens" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "b8609f9823edaffa2b1b7e2415e9b2bce3c356711ccb6c45f33c3b74f8438cc5"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b90ac0015a7f4a83d7ffaf97e17f0c6182973ca9d03e59cf6069e6dc40fc3677"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "42d2a9e516f504cf200eaf1e04206eb1d6ee4778329ac6f8fe8f6034aa8c8256"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "741ad98c5e4ae5bb9ecdcda4700b1ae0d5e3cb2f89ce91f0cf5065bc2e86a4cf"
      url "https://github.com/ConteMan/repolens/releases/download/v#{version}/repolens_#{version}_linux_arm64.tar.gz"
    end
  end

  name "repolens"
  desc "Turn any Git repository into a browsable static site"
  homepage "https://github.com/ConteMan/repolens"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "repolens"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/repolens"]
    end
  end

  # No zap stanza required

end
